# Generated by Django 3.1.4 on 2021-04-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_username', models.CharField(max_length=200)),
                ('request_method', models.CharField(max_length=50)),
                ('request_url', models.CharField(max_length=255)),
                ('request_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
