# Generated by Django 3.1.4 on 2021-04-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0002_auto_20210430_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='response_data',
            field=models.JSONField(default=dict),
        ),
    ]
