# Generated by Django 3.1.4 on 2021-05-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0003_log_response_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'permissions': [('can_search', 'Can search the web')], 'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
    ]
