# Generated by Django 3.1.4 on 2020-12-28 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('customer', '0002_employeemanagecustomer_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemanagecustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeManageCustomer_customer_field', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='employeemanagecustomer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeManageCustomer_employee_field', to='user.employee'),
        ),
    ]
