# Generated by Django 3.1.4 on 2021-04-30 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210415_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.location'),
        ),
    ]
