# Generated by Django 3.1.4 on 2021-07-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210524_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.TextField(default=''),
        ),
    ]
