# Generated by Django 3.1.4 on 2020-12-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.location'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
