# Generated by Django 3.1.4 on 2020-12-28 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliersupplyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplierSupplyProduct_product_field', to='product.product'),
        ),
        migrations.AlterField(
            model_name='suppliersupplyproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplierSupplyProduct_supplier_field', to='product.supplier'),
        ),
    ]
