# Generated by Django 3.1.4 on 2021-04-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210415_0657'),
        ('product', '0003_auto_20210420_0655'),
    ]

    operations = [
    ]
